import { doc, setDoc } from 'firebase/firestore';
import { db } from './firebase';

const doctors = [
  {
    doctorId: 'doc001',
    name: 'Dr. Aarav Sharma',
    email: 'aarav.sharma@hospital.com',
    specialization: 'Cardiologist',
    experience: '12 Years',
    clinicName: 'City Heart Hospital',
    clinicAddress: 'Civil Lines, Prayagraj',
    timing: '10:00 AM - 2:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    emailVerified: true,
    available: true,
    fees: '₹600',
    about: 'Experienced heart specialist with focus on preventive cardiology.',
  },
  {
    doctorId: 'doc002',
    name: 'Dr. Meera Kapoor',
    email: 'meera.kapoor@hospital.com',
    specialization: 'Dermatologist',
    experience: '9 Years',
    clinicName: 'Skin Care Hospital',
    clinicAddress: 'Lajpat Nagar, Delhi',
    timing: '11:00 AM - 4:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    emailVerified: true,
    available: true,
    fees: '₹500',
    about: 'Skin, hair and allergy specialist.',
  },
  {
    doctorId: 'doc003',
    name: 'Dr. Rohan Verma',
    email: 'rohan.verma@hospital.com',
    specialization: 'Orthopedic',
    experience: '14 Years',
    clinicName: 'Bone & Joint Hospital',
    clinicAddress: 'Noida Sector 62',
    timing: '9:30 AM - 1:30 PM',
    profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
    emailVerified: true,
    available: true,
    fees: '₹700',
    about: 'Specialist in bone, fracture and joint treatment.',
  },
  {
    doctorId: 'doc004',
    name: 'Dr. Ananya Singh',
    email: 'ananya.singh@hospital.com',
    specialization: 'Pediatrician',
    experience: '8 Years',
    clinicName: 'Kids Care Hospital',
    clinicAddress: 'Indirapuram, Ghaziabad',
    timing: '12:00 PM - 5:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/women/65.jpg',
    emailVerified: true,
    available: true,
    fees: '₹450',
    about: 'Child specialist for newborns to teenagers.',
  },
  {
    doctorId: 'doc005',
    name: 'Dr. Vikram Joshi',
    email: 'vikram.joshi@hospital.com',
    specialization: 'Neurologist',
    experience: '15 Years',
    clinicName: 'Brain & Nerve Hospital',
    clinicAddress: 'Hazratganj, Lucknow',
    timing: '10:30 AM - 3:30 PM',
    profileImage: 'https://randomuser.me/api/portraits/men/55.jpg',
    emailVerified: true,
    available: true,
    fees: '₹900',
    about: 'Expert in migraine, stroke and nervous system disorders.',
  },
  {
    doctorId: 'doc006',
    name: 'Dr. Pooja Malhotra',
    email: 'pooja.malhotra@hospital.com',
    specialization: 'Gynecologist',
    experience: '11 Years',
    clinicName: 'Women Wellness Hospital',
    clinicAddress: 'Vaishali, Ghaziabad',
    timing: '1:00 PM - 6:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/women/68.jpg',
    emailVerified: true,
    available: true,
    fees: '₹650',
    about: 'Women health and maternity care specialist.',
  },
  {
    doctorId: 'doc007',
    name: 'Dr. Kunal Bhatia',
    email: 'kunal.bhatia@hospital.com',
    specialization: 'ENT Specialist',
    experience: '10 Years',
    clinicName: 'ENT Care Hospital',
    clinicAddress: 'Karol Bagh, Delhi',
    timing: '9:00 AM - 1:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/men/61.jpg',
    emailVerified: true,
    available: true,
    fees: '₹500',
    about: 'Ear, nose and throat specialist.',
  },
  {
    doctorId: 'doc008',
    name: 'Dr. Nisha Arora',
    email: 'nisha.arora@hospital.com',
    specialization: 'Psychiatrist',
    experience: '7 Years',
    clinicName: 'Mind Care Hospital',
    clinicAddress: 'South Extension, Delhi',
    timing: '2:00 PM - 7:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/women/52.jpg',
    emailVerified: true,
    available: true,
    fees: '₹800',
    about: 'Mental wellness and stress management expert.',
  },
  {
    doctorId: 'doc009',
    name: 'Dr. Sarthak Jain',
    email: 'sarthak.jain@hospital.com',
    specialization: 'Dentist',
    experience: '6 Years',
    clinicName: 'Smile Dental Hospital',
    clinicAddress: 'Mathura Road, Agra',
    timing: '11:00 AM - 7:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/men/71.jpg',
    emailVerified: true,
    available: true,
    fees: '₹400',
    about: 'Dental cleaning, root canal and smile correction.',
  },
  {
    doctorId: 'doc010',
    name: 'Dr. Isha Tandon',
    email: 'isha.tandon@hospital.com',
    specialization: 'General Physician',
    experience: '13 Years',
    clinicName: 'Care Plus Hospital',
    clinicAddress: 'Aliganj, Lucknow',
    timing: '8:00 AM - 12:00 PM',
    profileImage: 'https://randomuser.me/api/portraits/women/75.jpg',
    emailVerified: true,
    available: true,
    fees: '₹350',
    about: 'General health, fever, infection and routine care specialist.',
  },
];

export const seedDoctorsToFirestore = async () => {
  try {
    console.log('🚀 Starting doctors upload...');

    for (const doctor of doctors) {
      await setDoc(doc(db, 'doctors', doctor.doctorId), doctor);
      console.log(`✅ Added: ${doctor.name}`);
    }

    console.log('🎉 All demo doctors added successfully');
    return { success: true };
  } catch (error) {
    console.log('❌ Error seeding doctors:', error);
    return { success: false, error };
  }
};